### ISSUE TITLE
Treffen No. 1

### ISSUE THREAD

**Issue by yyazgan** [ProPra16/programmierpraktikum-abschlussprojekt-team-2#2]
Hallo liebe Gruppe,

ich betreue euch. Bitte kommt doch in meine Übung am Freitag um 16:30 Uhr. 

Viele Grüße 

Yasin

**Comment by dasKeks** [comment]
Hallo Yasin,

in welchem Raum findet diese statt?

**Comment by yyazgan** [comment]
Da wo die Übungen stattfinden. Nebenan sind die Mathekästen. Müsste 25.13.00.81 sein.
